version: "3.3"

services:
  snikket_proxy:    
    environment:
      - SNIKKET_DOMAIN=foo.example.com
      - SNIKKET_ADMIN_EMAIL=admin@example.com
    container_name: snikket-proxy
    image: snikket/snikket-web-proxy:dev
    network_mode: host
    volumes:
      - snikket_data:/snikket
      - acme_challenges:/var/www/html/.well-known/acme-challenge
    restart: "unless-stopped"
    
  snikket_certs:
    environment:
      - SNIKKET_DOMAIN=foo.example.com
      - SNIKKET_ADMIN_EMAIL=admin@example.com
    container_name: snikket-certs
    image: snikket/snikket-cert-manager:dev
    network_mode: host
    volumes:
      - snikket_data:/snikket
      - acme_challenges:/var/www/.well-known/acme-challenge
    restart: "unless-stopped"
    
  snikket_portal:
    environment:
      - SNIKKET_DOMAIN=foo.example.com
      - SNIKKET_ADMIN_EMAIL=admin@example.com
    container_name: snikket-portal
    image: snikket/snikket-web-portal:dev
    network_mode: host
    restart: "unless-stopped"

  snikket_server:
    environment:
      - SNIKKET_DOMAIN=foo.example.com
      - SNIKKET_ADMIN_EMAIL=admin@example.com
    container_name: snikket
    image: snikket/snikket-server:dev
    network_mode: host
    volumes:
      - snikket_data:/snikket
    restart: "unless-stopped"

volumes:
  acme_challenges:
  snikket_data:
